services:
  app:
    build:
      context: .
      dockerfile: ./.docker/app/Dockerfile
    environment:
      APP_ENV: dev
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: "1"
      XDEBUG_MODE: "off"
      DATABASE_URL: "mysql://symfony:secret@db:3306/basket?serverVersion=8.0&charset=utf8mb4"
    volumes:
      - ./:/var/www/html:delegated
      - ./vendor:/var/www/html/vendor
    depends_on:
      db:
        condition: service_healthy

  web:
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:ro
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      app:
        condition: service_started

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: basket
      MYSQL_USER: symfony
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    command:
      [
        "--default-authentication-plugin=mysql_native_password",
        "--sql-mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
      ]
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER -p$$MYSQL_PASSWORD --silent" ]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  db_data:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
