openapi: 3.0.3
info:
    title: Basket API
    version: 1.0.0
paths:
    /api/baskets:
        post:
            summary: Create a new basket
            responses:
                '201':
                    description: Basket created
                    headers:
                        Location:
                            description: URL of the created basket
                            schema: { type: string, format: uri }
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id: { type: integer, example: 1 }
                                    createdAt: { type: string, format: date-time }
    /api/baskets/{id}:
        get:
            summary: Get a basket by id
            parameters:
                - in: path
                  name: id
                  required: true
                  schema: { type: integer }
            responses:
                '200':
                    description: Basket details
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id: { type: integer }
                                    createdAt: { type: string, format: date-time }
                                    items:
                                        type: array
                                        items:
                                            type: object
    /api/products:
        get:
            summary: Get a sorted list of all active products in stock
            responses:
                '200':
                    description: Basket details
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: object
                                    properties:
                                        id:
                                            type: integer
                                            example: 4
                                        name:
                                            type: string
                                            example: "27-inch Monitor"
                                        quantity:
                                            type: integer
                                            example: 10
                                        active:
                                            type: boolean
                                            example: true
                                        price:
                                            type: integer
                                            example: 19999
                            examples:
                                success:
                                    summary: Example product list
                                    value:
                                        -   id: 4
                                            name: "27-inch Monitor"
                                            quantity: 10
                                            active: true
                                            price: 19999
                                        -   id: 2
                                            name: "Mechanical Keyboard"
                                            quantity: 20
                                            active: true
                                            price: 7999
                                        -   id: 3
                                            name: "USB-C Cable"
                                            quantity: 100
                                            active: true
                                            price: 999
                                        -   id: 5
                                            name: "Webcam HD"
                                            quantity: 15
                                            active: true
                                            price: 4999
                                        -   id: 1
                                            name: "Wireless Mouse"
                                            quantity: 50
                                            active: true
                                            price: 2999
